# Generated by Django 4.1.1 on 2023-01-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlog', '0002_alter_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_type',
            field=models.CharField(blank=True, choices=[('Easy Run', 'Easy Run'), ('Long Run', 'Long Run'), ('Intervals', 'Intervals'), ('Tempo Run', 'Tempo Run')], default='Easy Run', max_length=20, null=True),
        ),
    ]
